SportsStore.WebUI/Models/CartIndexViewModel.cs
using SportsStore.Domain.Entities;

namespace SportsStore.WebUI.Models
{
    public class CartIndexViewModel
    {
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }
    }
}

SportsStore.WebUI/Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace SportsStore.WebUI.Models
{

    public class LoginViewModel
    {
        [Required] public string UserName { get; set; }

        [Required] public string Password { get; set; }
    }
}

SportsStore.WebUI/Models/PagingInfo.cs
using System;

namespace SportsStore.WebUI.Models
{

    public class PagingInfo
    {
        public int TotalItems { get; set; }
        public int ItemsPerPage { get; set; }
        public int CurrentPage { get; set; }

        public int TotalPages { get { return (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage); } }
    }
}

SportsStore.WebUI/Models/ProductsListViewModel.cs
using System.Collections.Generic;
using SportsStore.Domain.Entities;

namespace SportsStore.WebUI.Models
{
    public class ProductsListViewModel
    {

        public IEnumerable<Product> Products { get; set; }
        public PagingInfo PagingInfo { get; set; }
        public string CurrentCategory { get; set; }
    }
}

SportsStore.WebUI/Controllers/AccountController.cs
using SportsStore.WebUI.Infrastructure.Abstract;
using SportsStore.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportsStore.WebUI.Controllers
{
    public class AccountController : Controller
    {
        IAuthProvider authProvider;

        public AccountController(IAuthProvider auth) { authProvider = auth; }

        public ViewResult Login() { return View(); }

        [HttpPost]
        public ActionResult Login(LoginViewModel model, string returnUrl)
        {

            if (ModelState.IsValid) { if (authProvider.Authenticate(model.UserName, model.Password)) { return Redirect(returnUrl ?? Url.Action("Index", "Admin")); } else { ModelState.AddModelError("", "Incorrect username or password"); return View(); } } else { return View(); }
        }
    }
}

SportsStore.WebUI/Controllers/AdminController.cs
using System.Linq;
using System.Web.Mvc;
using SportsStore.Domain.Abstract;
using SportsStore.Domain.Entities;

namespace SportsStore.WebUI.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        private IProductRepository repository;

        public AdminController(IProductRepository repo)
        { 
            repository = repo;
        }

        public ViewResult Index()
        { 
            return View(repository.Products); 
        }

        public ViewResult Edit(int productId) 
        {
            Product product = repository.Products.FirstOrDefault(p => p.ProductID == productId);
            return View(product); 
        }
        [HttpPost]
        public ActionResult Edit(Product product)
        {
            if (ModelState.IsValid)
            {
                repository.SaveProduct(product);
                TempData["message"] = string.Format("{0} has been saved", product.Name);
                return RedirectToAction("Index");
            }
            else
            {
                return View(product);    
            } 
        }
        public ViewResult Create() { return View("Edit", new Product()); }
        [HttpPost] public ActionResult Delete(int productId) { Product deletedProduct = repository.DeleteProduct(productId); if (deletedProduct != null) { TempData["message"] = string.Format("{0} was deleted", deletedProduct.Name); } return RedirectToAction("Index"); }
    }
}

SportsStore.WebUI/Controllers/CartController.cs
using System.Linq;
using System.Web.Mvc;
using SportsStore.Domain.Abstract;
using SportsStore.Domain.Entities;
using SportsStore.WebUI.Models;

namespace SportsStore.WebUI.Controllers
{

    public class CartController : Controller
    {
        private IProductRepository repository;
        private IOrderProcessor orderProcessor;

        public CartController(IProductRepository repo, IOrderProcessor proc)
        {
            repository = repo;
            orderProcessor = proc;
        }

        
        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                ReturnUrl = returnUrl, Cart = cart
            });
        }

        public RedirectToRouteResult AddToCart(Cart cart, int productId, string returnUrl)
        {
            Product product = repository.Products.FirstOrDefault(p => p.ProductID == productId);

            if (product != null) { cart.AddItem(product, 1); }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int productId, string returnUrl)
        {
            Product product = repository.Products.FirstOrDefault(p => p.ProductID == productId);

            if (product != null)
            {

                cart.RemoveLine(product);

            }
            return RedirectToAction("Index", new { returnUrl });
        }


        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
            {
                if (cart.Lines.Count() == 0)
                {
                    ModelState.AddModelError("", "Sorry, your cart is empty!");
                }

                if (ModelState.IsValid)
                {
                    orderProcessor.ProcessOrder(cart, shippingDetails);
                    cart.Clear(); return View("Completed");
                }
                else
                {
                    return View(shippingDetails);
                }
            }
            public PartialViewResult Summary(Cart cart)
            {
                return PartialView(cart);
            }
        }
    } 

SportsStore.WebUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportsStore.WebUI.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

SportsStore.WebUI/Controllers/NavController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using SportsStore.Domain.Abstract;
using System.Linq;

namespace SportsStore.WebUI.Controllers
{

    public class NavController : Controller
    {
        private IProductRepository repository;

        public NavController(IProductRepository repo)
        { 
            repository = repo; 
        }

        public PartialViewResult Menu(string category = null)
        {

            ViewBag.SelectedCategory = category;

            IEnumerable<string> categories = repository.Products.Select(x => x.Category).Distinct().OrderBy(id=>id);
            
            
            foreach (var item in categories)
            {
                System.Console.WriteLine(item);
            }
            return PartialView(categories);
        }
    }
}

SportsStore.WebUI/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SportsStore.Domain.Abstract;
using SportsStore.Domain.Entities;
using SportsStore.WebUI.Models;

namespace SportsStore.WebUI.Controllers
{

    public class ProductController : Controller
    {
        private IProductRepository repository;
        public int PageSize = 3;

        public ProductController(IProductRepository productRepository) { this.repository = productRepository; }

        public ViewResult List(string category, int page = 1)
        {
            ProductsListViewModel model = new ProductsListViewModel
            { 
                Products = repository.Products.Where(p => category == null || p.Category == category).OrderBy(p => p.ProductID).Skip((page - 1) * PageSize).Take(PageSize),
                PagingInfo = new PagingInfo { 
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = category == null ? 
                    repository.Products.Count() :
                    repository.Products.Where(e => e.Category == category).Count()
                }, 
                CurrentCategory = category
            };
            return View(model);
        }
    }
}

SportsStore.WebUI/Views/Admin/Edit.cshtml
@model SportsStore.Domain.Entities.Product

@{ ViewBag.Title = "Admin: Edit " + @Model.Name; Layout = "~/Views/Shared/_AdminLayout.cshtml"; }

<div class="panel">
    <div class="panel-heading">        <h3>Edit @Model.Name</h3>    </div>

    @using (Html.BeginForm("Edit", "Admin"))
    {<div class="panel-body">
            @foreach (var property in ViewData.ModelMetadata.Properties)
            {
                if (property.PropertyName != "ProductID")
                {<div class="form-group">
                        <label>@(property.DisplayName ?? property.PropertyName)</label>     
                @if (property.PropertyName == "Description")
                        {@Html.TextArea(property.PropertyName, null, new { @class = "form-control", rows = 5 }) }
                    else
                    { @Html.TextBox(property.PropertyName, null, new { @class = "form-control" })}                    @Html.ValidationMessage(property.PropertyName)
                </div>}
        }
        </div>
        <div class="panel-footer">      
    <input type="submit" value="Save" class="btn btn-primary" /> 
    @Html.ActionLink("Cancel and return to List", "Index", null, new { @class = "btn btn-default" })  
            </div>}
</div>

SportsStore.WebUI/Views/Admin/Index.cshtml
@model IEnumerable<SportsStore.Domain.Entities.Product>

@{
    ViewBag.Title = "Admin: All Products"; 
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    }
<div class="panel panel-default">

    <div class="panel-heading">
        <h3>All Products</h3>
    </div>
    <div class="panel-body">

        <table class="table table-striped table-condensed table-bordered">
            <tr>
                <th class="text-right">ID</th>
                <th>Name</th>
                <th class="text-right">Price</th>
                <th class="text-center">Actions</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-right">@item.ProductID</td>

                    <td>@Html.ActionLink(item.Name, "Edit", new { item.ProductID })</td>
                    <td class="text-right">@item.Price.ToString("c")</td>
                    <td class="text-center">
                        @using (Html.BeginForm("Delete", "Admin"))

                         {
                          
                            @Html.Hidden("ProductID", item.ProductID) 
                            <input type="submit" class="btn btn-default btn-xs" value="Delete" />
                         }
                    </td>
                </tr>
}
        </table>
    </div>
    <div class="panel-footer">
        @Html.ActionLink("Add a new product", "Create", null, new { @class = "btn btn-default" })
    </div>
</div>

SportsStore.WebUI/Views/Cart/Checkout.cshtml
@model SportsStore.Domain.Entities.ShippingDetails

@{
    ViewBag.Title = "Checkout";
}
<head>
    <link rel="stylesheet" type="text/css" href="~/Content/Styles.css" />
</head>
<h2>Checkout</h2>
<p>Please enter your details, and we'll ship your goods right away!</p>
@using (Html.BeginForm())

{
    @Html.ValidationSummary()
<h3>Ship to</h3>
<div class="form-group">
    <label>Name:</label>
    @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
</div>

<h3>Address</h3>

foreach (var property in ViewData.ModelMetadata.Properties)
{
    if (property.PropertyName != "Name" && property.PropertyName != "GiftWrap")
    { <div class="form-group">
            <label>@(property.DisplayName ?? property.PropertyName)</label>
            @Html.TextBox(property.PropertyName, null, new { @class = "form-control" })
        </div>
    }
}
<h3>Options</h3>
<div class="checkbox">
    <label>
        @Html.EditorFor(x => x.GiftWrap)
        Gift wrap these items
    </label>
</div>

<div class="text-center">
    <input class="btn btn-primary" type="submit" value="Complete order" />
</div>}

SportsStore.WebUI/Views/Cart/Completed.cshtml
@{ ViewBag.Title = "SportsStore: Order Submitted"; }

<h2>Thanks!</h2> 
Thanks for placing your order. We'll ship your goods as soon as possible.

SportsStore.WebUI/Views/Cart/Index.cshtml
@model SportsStore.WebUI.Models.CartIndexViewModel

@{ ViewBag.Title = "Sports Store: Your Cart"; }
<style>
    #cartTable td {
        vertical-align: middle;
    }
</style>

<h2>Your cart</h2>
<label>Current Long Date: @DateTime.Now.ToLongDateString()</label>
<br />
<table id="cartTable" class="table">

    <thead>
        <tr>
            <th>Quantity</th>

            <th>Item</th>
            <th class="text-right">Price</th>
            <th class="text-right">Subtotal</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.Cart.Lines)
        {
            <tr>
                <td class="text-center">@line.Quantity</td>
                <td class="text-left">@line.Product.Name</td>
                <td class="text-right">@line.Product.Price.ToString("c")</td>
                <td class="text-right">
                    @((line.Quantity * line.Product.Price).ToString("c"))
                </td>

                <td>
                    @using (Html.BeginForm("RemoveFromCart", "Cart"))
                    {
                        @Html.Hidden("ProductId", line.Product.ProductID)
                        @Html.HiddenFor(x => x.ReturnUrl)
                        <input class="btn btn-sm btn-warning" type="submit" value="Remove" />
                    }
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Total:</td>
            <td class="text-right">
                @Model.Cart.ComputeTotalValue().ToString("c")
            </td>
        </tr>
    </tfoot>

</table>
<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue shopping</a>
    @Html.ActionLink("Checkout now", "Checkout", null, new { @class = "btn btn-primary" })
</div>

SportsStore.WebUI/Views/Cart/Summary.cshtml
@model SportsStore.Domain.Entities.Cart

<div class="navbar-right">  
    @Html.ActionLink("Checkout", "Index", "Cart", 
    new { returnUrl = Request.Url.PathAndQuery },
    new { @class = "btn btn-default navbar-btn" }) 
</div>

<div class="navbar-text navbar-right">   
    <b>Your cart:</b>  
    @Model.Lines.Sum(x => x.Quantity) item(s), 
    @Model.ComputeTotalValue().ToString("c")
 </div>

SportsStore.WebUI/Views/Nav/Menu.cshtml
@model IEnumerable<string>

@Html.ActionLink("Home", "List", "Product", null, new { @class = "btn btn-block btn-default btn-lg" })

@foreach (var link in Model)
{
    @Html.RouteLink(link, new
{
    controller = "Product",
    action = "List",
    category = link, page = 1
},
new
{
    @class = "btn btn-block btn-default btn-lg"
     + (link == ViewBag.SelectedCategory ? " btn-primary" : "")
}
)
}

SportsStore.WebUI/Views/Product/List.cshtml
@model SportsStore.WebUI.Models.ProductsListViewModel

@{ ViewBag.Title = "Products"; }

@foreach (var p in Model.Products)
{@Html.Partial("ProductSummary", p)}

<div class="pager">
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("List", new { page = x, category = Model.CurrentCategory }))
</div>

SportsStore.WebUI/Views/Shared/ProductSummary.cshtml
@model SportsStore.Domain.Entities.Product

<div class="well">
    <h3>
        <strong>@Model.Name</strong>
        <span class="pull-right label label-primary">@Model.Price.ToString("c")</span>
    </h3>
    @using (Html.BeginForm("AddToCart", "Cart"))
    {
        <div class="pull-right">    
    @Html.HiddenFor(x => x.ProductID)   
    @Html.Hidden("returnUrl", Request.Url.PathAndQuery)    
    <input type="submit" class="btn btn-success" value="Add to cart" /> 
            </div>
            }

    <span class="lead"> @Model.Description</span>

</div>

SportsStore.WebUI/Views/Shared/_AdminLayout.cshtml
@{ Layout = null; }

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.9.1.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <title></title>
</head>
<body>
    <div>
        @if (TempData["message"] != null)
         {
            <div class="alert alert-success">
        @TempData["message"]
            </div>
         }
        @RenderBody()
    </div>
</body>
</html>

SportsStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="#">SPORTS STORE</a>
        @Html.Action("Summary", "Cart")
    </div>   
    <div class="row panel">   
        <div id="categories" class="col-xs-3">
            @Html.Action("Menu", "Nav")
        </div>     
    <div class="col-xs-8">    
    @RenderBody()      
                    </div>   
    </div>
</body>
</html>